<?php

namespace Alex\UsersBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends EntityRepository {

    public function getPatients($filter = null) {
        $qb = $this->createQueryBuilder('p')
//                ->where('p.active = :active')
//                ->setParameter('active', $active)
                ->orderBy('p.id', 'DESC');

//        if ($max) {
//            $qb->setMaxResults($max);
//        }
//        if ($offset) {
//            $qb->setFirstResult($offset);
//        }
        if ($filter->getHospital_id()) {
            $qb->andWhere('p.hospital = :hospital_id')
                    ->setParameter('hospital_id', $filter->getHospital_id());
        }
        if ($filter->getName()) {
            $qb->andWhere($qb->expr()->like('p.name', ':name'))
                    ->setParameter('name', '%'.$filter->getName().'%');
        }

        $query = $qb->getQuery();

        return $query->getResult();
    }

}
